language: node_js
node_js:
  - 10
cache:
  npm: true
  directories:
    - ~/.cache
install:
  - npm ci
  - npm run install:test
script:
  - npm start & $(npm bin)/wait-on http://localhost:1234
  - $(npm bin)/cypress run --record
